server:
  port: 5000

spring:
  jpa:
    database: Oracle
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@//${rds.hostname}:${rds.port}/${rds.service.name}
    username: ${rds.username}
    password: ${rds.password}