server:
  port: 5000

spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

  # DataSource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${rds.username}
    password: ${rds.password}